### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alisterburt** [teamtomo/cryohub#3]
Hey - would you consider relicensing this repo under BSD-3? Ideally I would prefer it if all of the teamtomo repos had the same license, didn't realise this was different

**Comment by brisvag** [comment]
In general, if we want this org to be a place for people to contribute and put their own projects, I think we should let everyone license however they prefer.

Specifically, you know how I feel about open source licenses, so I would prefer to keep this copyleft :P

**Comment by alisterburt** [comment]
I agree that people should be able to license their projects as they like but the teamtomo project is about maximising reuse across the ecosystem - it's specifically for small, reusable components and not for peoples entire projects

We know for a fact large swathes of people, including many we respect in OSS (Juan, Talley etc), won't look at/depend on GPL'd code - if we really believe in maximising reuse alienating people in this camp before the project is off the ground feels irresponsible and it only has the potential to hamstring us.

With that in mind I've added a note to the org page saying that projects in the org should be licensed under the 3-Clause BSD license - could you please either relicense or move `cryohub` out of the org

**Comment by brisvag** [comment]
> We know for a fact large swathes of people, including many we respect in OSS (Juan, Talley etc), won't look at/depend on GPL'd code

Yes, but I think they are wrong, though :P reminder that RELION is GPL licensed, just like linux , git, ssh, and a million other hugely pervasive software that most of the IT world depends on. Being GPL was not an obstacle: it is what brought their success, because it forced the community to give back to the source, instead of locking up behind a paywall and slowly dying in the dark. The only leverage that closed-source, for-profit projects have on the open source community is whatever leverage we're willing to give them... and BSD gives them *everything*.

I do realise that unfortunately *many* people are convinced by the anti-copyleft rethoric, even if they are the ones giving up something for it. So I know that by choosing GPL, you are distancing well-meaning open source contributors, and not only those who want to take advantage of the open source community. However, I don't think that just giving up on it is a good compromise.

I agree that something like cryotypes, as a specification, should be BSD to maximize buy-in, so even non-OSS can easily follow it and help the ecosystem grow. However, anything that's not a spec but actual implementation, is different. I have zero interest in pushing science into the hands of the private sector so it can be strangled by greed more than it already is. #OpenSoftwareAcceleratesScience :)

So, I think it's a mistake to straight up only allow BSD on the org; people can choose their dependencies as they wish, it's not like you're forced to depend on every teamtomo package. I was actually thinking of adding `blik` here as well... I think blocking non-bsd software in here would bring exactly zero benefit, and only prevent some people who agree with me from making their projects more visible and accessible.

**Comment by alisterburt** [comment]
for anyone reading this, some discussion has continued in private

re: blik: I don't think user facing software (i.e. for non-python users) belongs in this org, this is a choice made specifically so that the incentive structures for contributing something vs. developing your own thing work out nicely. A major reason for not contributing to OSS is that people feel the need for 'inventing their own thing'. With this model, any individual or lab gets all of the credit for the thing users interact with and we/the rest of the scientific python ecosystem benefit from any contributions made upstream. Another benefit is that the effort for integrating and subsequent maintenance burden of small, well scoped pieces rather than larger packages is much smaller

**Comment by brisvag** [comment]
Yup, I agree on what belongs in teamtomo and what doesn't; I would also add that for anything in the "gray area", I would lean toward inclusion rather than exclusion, for visibility and adoption's sake, but I guess that's going to be on a case by case basis.

**Comment by alisterburt** [comment]
follow up after discussion offline, we agreed that the correct path for something in the 'gray area' was to find the small reusable thing and help the person piece it out rather than include something not well scoped

closing this
